### ISSUE TITLE
Heading CSS

### ISSUE THREAD

**Issue by 23727** [liamcain/obsidian-creases#14]
Hello,

Can you share your theme and css mods featured in the readme, please:

![](https://user-images.githubusercontent.com/693981/156103767-33f311de-39ac-422d-b8ea-987ea9c63f7b.png)

It looks awesome, and I find it a plus that it indicates the header level–very helpful. Thank you!

**Comment by liamcain** [comment]
The snippet for that is:

```css
.HyperMD-header.cm-line {
  position: relative;
}

.HyperMD-header.cm-line::before {
  color: var(--text-muted);
  font-size: 0.7rem;
  left: -2.8em;
  letter-spacing: 0.2px;
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
}

.HyperMD-header.HyperMD-header-1.cm-line::before {
  content: "H1";
}
.HyperMD-header.HyperMD-header-2.cm-line::before {
  content: "H2";
}
.HyperMD-header.HyperMD-header-3.cm-line::before {
  content: "H3";
}
.HyperMD-header.HyperMD-header-4.cm-line::before {
  content: "H4";
}
.HyperMD-header.HyperMD-header-5.cm-line::before {
  content: "H5";
}
.HyperMD-header.HyperMD-header-6.cm-line::before {
  content: "";
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='%236272a4' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' class='feather feather-list'%3E%3Cline x1='8' y1='6' x2='21' y2='6'%3E%3C/line%3E%3Cline x1='8' y1='12' x2='21' y2='12'%3E%3C/line%3E%3Cline x1='8' y1='18' x2='21' y2='18'%3E%3C/line%3E%3Cline x1='3' y1='6' x2='3.01' y2='6'%3E%3C/line%3E%3Cline x1='3' y1='12' x2='3.01' y2='12'%3E%3C/line%3E%3Cline x1='3' y1='18' x2='3.01' y2='18'%3E%3C/line%3E%3C/svg%3E");
  background-size: 12px 12px;
  width: 12px;
  height: 12px;
}
```

But since a lot of people have asked me about that snippet, I turned it into a plugin: https://github.com/liamcain/obsidian-heading-markers.
