### ISSUE TITLE
FR: ability to change lucide icon in settings

### ISSUE THREAD

**Issue by riddlew** [liamcain/obsidian-creases#46]
Would it be possible to add an option in the settings to change the lucide icon used for creases. I'm not a fan of having shirt icons throughout my notes, and wanted to change it to something a little more minimal.

**Comment by nydcroxas** [comment]
Any update on this? I've been looking for a fix but no luck.

**Comment by sicahjes** [comment]
Wish we didn't have to have an icon at all. This plugin won't be usable for me until the icon is removed.

**Comment by FeralFlora** [comment]
This [CSS snippet](https://help.obsidian.md/Extending+Obsidian/CSS+snippets) hides the shirt icon:

```css
.cm-creases-icon {
    display: none;
}
```

**Comment by Iwuaa** [comment]
I would love this feature, shirt icon is out of place a bit

**Comment by mattmaiorana** [comment]
Anybody every figure out how to do this?

**Comment by yett1873** [comment]
> I would love this feature, shirt icon is out of place a bit

This one should work. Just replace the URL with whatever icon you like from https://lucide.dev/icons/

```css
.svg-icon.lucide-shirt {
  color: transparent;
}
.cm-creases-icon{
  background: url(
    data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIyIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIGNsYXNzPSJsdWNpZGUgbHVjaWRlLWdyaXAiPjxjaXJjbGUgY3g9IjEyIiBjeT0iNSIgcj0iMSIvPjxjaXJjbGUgY3g9IjE5IiBjeT0iNSIgcj0iMSIvPjxjaXJjbGUgY3g9IjUiIGN5PSI1IiByPSIxIi8+PGNpcmNsZSBjeD0iMTIiIGN5PSIxMiIgcj0iMSIvPjxjaXJjbGUgY3g9IjE5IiBjeT0iMTIiIHI9IjEiLz48Y2lyY2xlIGN4PSI1IiBjeT0iMTIiIHI9IjEiLz48Y2lyY2xlIGN4PSIxMiIgY3k9IjE5IiByPSIxIi8+PGNpcmNsZSBjeD0iMTkiIGN5PSIxOSIgcj0iMSIvPjxjaXJjbGUgY3g9IjUiIGN5PSIxOSIgcj0iMSIvPjwvc3ZnPg==
    );
  background-repeat: no-repeat;
  background-size: .7em;
  background-position: 5% 75%;
}
```
